package com.hibernate.model;

// Generated Jun 16, 2015 7:33:04 PM by Hibernate Tools 3.4.0.CR1

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private int empId;
	private Employee employee;
	private String addressLine1;
	private String zipcode;
	private String city;

	public Address() {
	}

	public Address(Employee employee, String addressLine1) {
		this.employee = employee;
		this.addressLine1 = addressLine1;
	}

	public Address(Employee employee, String addressLine1, String zipcode,
			String city) {
		this.employee = employee;
		this.addressLine1 = addressLine1;
		this.zipcode = zipcode;
		this.city = city;
	}

	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

}
