package com.hibernate.model;

// Generated Jun 15, 2015 8:58:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart implements java.io.Serializable {

	private Integer cartId;
	private long cartTotal;
	private Set items = new HashSet(0);

	public Cart() {
	}

	public Cart(long cartTotal) {
		this.cartTotal = cartTotal;
	}

	public Cart(long cartTotal, Set items) {
		this.cartTotal = cartTotal;
		this.items = items;
	}

	public Integer getCartId() {
		return this.cartId;
	}

	public void setCartId(Integer cartId) {
		this.cartId = cartId;
	}

	public long getCartTotal() {
		return this.cartTotal;
	}

	public void setCartTotal(long cartTotal) {
		this.cartTotal = cartTotal;
	}

	public Set getItems() {
		return this.items;
	}

	public void setItems(Set items) {
		this.items = items;
	}

}
