package com.hibernate.model;

// Generated Jun 14, 2015 8:57:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Employee generated by hbm2java
 */
public class EmployeeOls  {

	private Integer id;
	private String name;
	private String role;
	private Date insertTime;

	public EmployeeOls() {
	}

	public EmployeeOls(String name, String role, Date insertTime) {
		this.name = name;
		this.role = role;
		this.insertTime = insertTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

}
