package com.hibernate.model;

// Generated Jun 16, 2015 7:33:04 PM by Hibernate Tools 3.4.0.CR1

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private Integer empId;
	private String empName;
	private double empSalary;
	private Address address;

	public Employee() {
	}

	public Employee(String empName, double empSalary) {
		this.empName = empName;
		this.empSalary = empSalary;
	}

	public Employee(String empName, double empSalary, Address address) {
		this.empName = empName;
		this.empSalary = empSalary;
		this.address = address;
	}

	public Integer getEmpId() {
		return this.empId;
	}

	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	public double getEmpSalary() {
		return this.empSalary;
	}

	public void setEmpSalary(double empSalary) {
		this.empSalary = empSalary;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

}
