package com.hibernate.model;

// Generated Jun 15, 2015 8:58:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable {

	private Integer itemId;
	private String itemDesc;
	private long itemPrice;
	private Set carts = new HashSet(0);

	public Item() {
	}

	public Item(String itemDesc, long itemPrice) {
		this.itemDesc = itemDesc;
		this.itemPrice = itemPrice;
	}

	public Item(String itemDesc, long itemPrice, Set carts) {
		this.itemDesc = itemDesc;
		this.itemPrice = itemPrice;
		this.carts = carts;
	}

	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	public String getItemDesc() {
		return this.itemDesc;
	}

	public void setItemDesc(String itemDesc) {
		this.itemDesc = itemDesc;
	}

	public long getItemPrice() {
		return this.itemPrice;
	}

	public void setItemPrice(long itemPrice) {
		this.itemPrice = itemPrice;
	}

	public Set getCarts() {
		return this.carts;
	}

	public void setCarts(Set carts) {
		this.carts = carts;
	}

}
