package com.hibernate.model;

// Generated Jun 15, 2015 8:17:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class Transaction  {

	private Integer txnId;
	private Date txnDate;
	private long txnTotal;
	private Customer customer;

	public Transaction() {
	}

	public Transaction(Date txnDate, long txnTotal) {
		this.txnDate = txnDate;
		this.txnTotal = txnTotal;
	}

	public Transaction(Date txnDate, long txnTotal, Customer customer) {
		this.txnDate = txnDate;
		this.txnTotal = txnTotal;
		this.customer = customer;
	}

	public Integer getTxnId() {
		return this.txnId;
	}

	public void setTxnId(Integer txnId) {
		this.txnId = txnId;
	}

	public Date getTxnDate() {
		return this.txnDate;
	}

	public void setTxnDate(Date txnDate) {
		this.txnDate = txnDate;
	}

	public long getTxnTotal() {
		return this.txnTotal;
	}

	public void setTxnTotal(long txnTotal) {
		this.txnTotal = txnTotal;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

}
